artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1ORlqNeY3OnD7nHNDJ_NTN93QvyurvZvh/view?usp=sharing
  local_datafile: artifacts/data_ingestion/fsd.zip
  unzip_dir: artifacts/data_ingestion

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/updated_base_model.h5
  updated_base_model_image_path: artifacts/prepare_base_model/updated_base_model.png

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5