artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1wUOvq1aDOx8qyERt7L2d2taeaVAiV6Le/view?usp=sharing
  local_datafile: artifacts/data_ingestion/food_spoilage.rar
  unzip_dir: artifacts/data_ingestion

data_preprocessing:
  root_dir: artifacts/data_preprocessing
  unzip_dir: artifacts/data_ingestion
  reshape_dir: artifacts/data_preprocessing
  image_size: [224, 244]

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/updated_base_model.h5
  updated_base_model_image_path: artifacts/prepare_base_model/updated_base_model.png

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5

model_evaluation:
  root_dir: artifacts/model_evaluation
  trained_model_path: artifacts/training/model.h5
  training_data: artifacts/data_preprocessing/Food_Spoilage_Dataset
  report_file: artifacts/model_evaluation/report.json
